apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: manager
  labels:
    app: manager
  namespace: cchess
spec:
  selector:
    matchLabels:
      app: manager
  replicas: 1
  serviceName: "manager"
  template:
    metadata:
      labels:
        app: manager
    spec:
      dnsPolicy: Default
      containers:
        - name: match-manager
          image: 'docker.pkg.github.com/elvisigkeit/match_manager/match_manager:0.2'
          ports:
            - containerPort: 8000
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              host: ''
              path: /
              port: 8000
              scheme: ''
      imagePullSecrets:
        - name: regcred